// import { type WorkspaceNodeData } from "./workspace-canvas-store";

import type { WorkspaceNodeData } from "./store/workspace-canvas-store";

const WORKSPACE_ID = "ws_civil_engine_001";
const ROOT_ID = "root_001";

export const mockWorkspaceNodes: WorkspaceNodeData[] = [
    // ─── ROOT ─────────────────────────────────────────────────────────────
    {
        id: ROOT_ID,
        workspaceId: WORKSPACE_ID,
        parentId: null,
        nodeType: "ROOT",
        name: "Workspace Root",
        description: null,
        icon: null,
        color: null,
        linkedWorkflowId: null,
        linkedVersion: null,
        sortOrder: 0,
        path: `/${ROOT_ID}`,
        depth: 0,
        isExpanded: true,
        canvasX: 0,
        canvasY: 0,
        metadata: {},
    },

    // ─── TOP LEVEL CATEGORIES (Folders) ───────────────────────────────────
    {
        id: "cat_flood_discharge",
        workspaceId: WORKSPACE_ID,
        parentId: ROOT_ID,
        nodeType: "FOLDER",
        name: "Flood Discharge",
        description: "Main flood discharge calculation methods",
        icon: "🌊",
        color: null,
        linkedWorkflowId: null,
        linkedVersion: null,
        sortOrder: 0,
        path: `/${ROOT_ID}/cat_flood_discharge`,
        depth: 1,
        isExpanded: true,
        canvasX: 400,
        canvasY: 50,
        metadata: {},
    },
    {
        id: "cat_rainfall",
        workspaceId: WORKSPACE_ID,
        parentId: ROOT_ID,
        nodeType: "FOLDER",
        name: "Rainfall Analysis",
        description: null,
        icon: "🌧️",
        color: null,
        linkedWorkflowId: null,
        linkedVersion: null,
        sortOrder: 1,
        path: `/${ROOT_ID}/cat_rainfall`,
        depth: 1,
        isExpanded: true,
        canvasX: 800,
        canvasY: 50,
        metadata: {},
    },
    {
        id: "cat_scour",
        workspaceId: WORKSPACE_ID,
        parentId: ROOT_ID,
        nodeType: "FOLDER",
        name: "Scour Assessment",
        description: null,
        icon: "🌉",
        color: null,
        linkedWorkflowId: null,
        linkedVersion: null,
        sortOrder: 2,
        path: `/${ROOT_ID}/cat_scour`,
        depth: 1,
        isExpanded: true,
        canvasX: 1050,
        canvasY: 50,
        metadata: {},
    },

    // ─── FLOOD DISCHARGE SUBCATEGORIES ────────────────────────────────────
    {
        id: "sub_empirical",
        workspaceId: WORKSPACE_ID,
        parentId: "cat_flood_discharge",
        nodeType: "FOLDER",
        name: "Empirical",
        description: null,
        icon: "🧮",
        color: null,
        linkedWorkflowId: null,
        linkedVersion: null,
        sortOrder: 0,
        path: `/${ROOT_ID}/cat_flood_discharge/sub_empirical`,
        depth: 2,
        isExpanded: true,
        canvasX: 200,
        canvasY: 200,
        metadata: {},
    },
    {
        id: "sub_hydrograph",
        workspaceId: WORKSPACE_ID,
        parentId: "cat_flood_discharge",
        nodeType: "FOLDER",
        name: "Unit Hydrograph",
        description: null,
        icon: "📈",
        color: null,
        linkedWorkflowId: null,
        linkedVersion: null,
        sortOrder: 1,
        path: `/${ROOT_ID}/cat_flood_discharge/sub_hydrograph`,
        depth: 2,
        isExpanded: true,
        canvasX: 500,
        canvasY: 200,
        metadata: {},
    },
    {
        id: "sub_frequency",
        workspaceId: WORKSPACE_ID,
        parentId: "cat_flood_discharge",
        nodeType: "FOLDER",
        name: "Flood Frequency Analysis",
        description: null,
        icon: "📊",
        color: null,
        linkedWorkflowId: null,
        linkedVersion: null,
        sortOrder: 2,
        path: `/${ROOT_ID}/cat_flood_discharge/sub_frequency`,
        depth: 2,
        isExpanded: true,
        canvasX: 750,
        canvasY: 200,
        metadata: {},
    },

    // ─── EMPIRICAL REGIONS ───────────────────────────────────────────────
    {
        id: "reg_indian",
        workspaceId: WORKSPACE_ID,
        parentId: "sub_empirical",
        nodeType: "FOLDER",
        name: "Indian",
        description: null,
        icon: "🇮🇳",
        color: null,
        linkedWorkflowId: null,
        linkedVersion: null,
        sortOrder: 0,
        path: `/${ROOT_ID}/cat_flood_discharge/sub_empirical/reg_indian`,
        depth: 3,
        isExpanded: true,
        canvasX: 100,
        canvasY: 350,
        metadata: {},
    },
    {
        id: "reg_uk",
        workspaceId: WORKSPACE_ID,
        parentId: "sub_empirical",
        nodeType: "FOLDER",
        name: "UK",
        description: null,
        icon: "🇬🇧",
        color: null,
        linkedWorkflowId: null,
        linkedVersion: null,
        sortOrder: 1,
        path: `/${ROOT_ID}/cat_flood_discharge/sub_empirical/reg_uk`,
        depth: 3,
        isExpanded: true,
        canvasX: 350,
        canvasY: 350,
        metadata: {},
    },

    // ─── INDIAN FORMULAS (Workflow Links representing DSL execution) ─────
    {
        id: "form_dickens",
        workspaceId: WORKSPACE_ID,
        parentId: "reg_indian",
        nodeType: "WORKFLOW_LINK",
        name: "Dicken's Formula",
        description: "Q = C × M^(3/4)",
        icon: "ƒ",
        color: null,
        linkedWorkflowId: "dsl_dickens_v1",
        linkedVersion: null,
        sortOrder: 0,
        path: `/${ROOT_ID}/cat_flood_discharge/sub_empirical/reg_indian/form_dickens`,
        depth: 4,
        isExpanded: false,
        canvasX: 50,
        canvasY: 500,
        metadata: { formula: "Q = C * M^(3/4)", status: "active" },
    },
    {
        id: "form_ryves",
        workspaceId: WORKSPACE_ID,
        parentId: "reg_indian",
        nodeType: "WORKFLOW_LINK",
        name: "Ryve's Formula",
        description: "Q = C × M^(2/3)",
        icon: "ƒ",
        color: null,
        linkedWorkflowId: "dsl_ryves_v1",
        linkedVersion: null,
        sortOrder: 1,
        path: `/${ROOT_ID}/cat_flood_discharge/sub_empirical/reg_indian/form_ryves`,
        depth: 4,
        isExpanded: false,
        canvasX: 50,
        canvasY: 580,
        metadata: { formula: "Q = C * M^(2/3)", status: "active" },
    },
    {
        id: "form_inglis",
        workspaceId: WORKSPACE_ID,
        parentId: "reg_indian",
        nodeType: "WORKFLOW_LINK",
        name: "Ingli's Formula",
        description: "Q = 125M / √(M+10)",
        icon: "ƒ",
        color: null,
        linkedWorkflowId: "dsl_inglis_v1",
        linkedVersion: null,
        sortOrder: 2,
        path: `/${ROOT_ID}/cat_flood_discharge/sub_empirical/reg_indian/form_inglis`,
        depth: 4,
        isExpanded: false,
        canvasX: 50,
        canvasY: 660,
        metadata: { formula: "Q = 125M / sqrt(M+10)", status: "active" },
    },
    {
        id: "form_creagers",
        workspaceId: WORKSPACE_ID,
        parentId: "reg_indian",
        nodeType: "WORKFLOW_LINK",
        name: "Creager's Formula",
        description: "Q = C(0.386A)^0.894",
        icon: "ƒ",
        color: null,
        linkedWorkflowId: "dsl_creagers_v1",
        linkedVersion: null,
        sortOrder: 3,
        path: `/${ROOT_ID}/cat_flood_discharge/sub_empirical/reg_indian/form_creagers`,
        depth: 4,
        isExpanded: false,
        canvasX: 50,
        canvasY: 740,
        metadata: { formula: "Q = C(0.386A)^0.894...", status: "active" },
    },
    {
        id: "form_rational",
        workspaceId: WORKSPACE_ID,
        parentId: "reg_indian",
        nodeType: "WORKFLOW_LINK",
        name: "Modified Rational",
        description: "Q = 0.028·P·f·A·Ic",
        icon: "⚡",
        color: null,
        linkedWorkflowId: "dsl_mod_rational_v2", // This points to the workflow detailed at the bottom of the image
        linkedVersion: null,
        sortOrder: 4,
        path: `/${ROOT_ID}/cat_flood_discharge/sub_empirical/reg_indian/form_rational`,
        depth: 4,
        isExpanded: false,
        canvasX: 50,
        canvasY: 820,
        metadata: {
            formula: "Q = 0.028*P*f*A*Ic",
            status: "active",
            badge: "SELECTED"
        },
        linkedWorkflow: {
            id: "dsl_mod_rational_v2",
            name: "Rational Engine Pipeline",
            status: "active",
            category: "Calculations"
        }
    },

    // ─── ANNOTATION NOTE (From the left side of the image) ────────────────
    {
        id: "note_ux_rules",
        workspaceId: WORKSPACE_ID,
        parentId: ROOT_ID,
        nodeType: "NOTE",
        name: "UX Rules",
        description: null,
        icon: null,
        color: "#f8fafc",
        linkedWorkflowId: null,
        linkedVersion: null,
        sortOrder: 10,
        path: `/${ROOT_ID}/note_ux_rules`,
        depth: 1,
        isExpanded: false,
        canvasX: -200,
        canvasY: 350,
        metadata: {
            noteContent: "- We only need to ask the related field\n- Show only final values\n- It may have Graph\n- It may ask for values, which is required to for flow"
        },
    }
];

// Mock backend workflows for the search dialog
export const mockDatabaseWorkflows = [
    { id: "dsl_dickens_v1", name: "Dicken's Evaluation Node", category: "Calculations" },
    { id: "dsl_ryves_v1", name: "Ryve's Math Engine", category: "Calculations" },
    { id: "dsl_inglis_v1", name: "Ingli's Square Root Resolver", category: "Calculations" },
    { id: "dsl_creagers_v1", name: "Creager's Power Function", category: "Calculations" },
    { id: "dsl_mod_rational_v2", name: "Rational Engine Pipeline", category: "Calculations" },
    { id: "ui_input_collector", name: "Dynamic Form Generator", category: "UI Nodes" },
];